name: Test

on: [push, pull_request]

env:
  GO_VERSION: 1.17

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-20.04'
        arch:
          - 'x86_64'
    steps:
    - uses: actions/checkout@v2
    - name: Set up go-version 1.17
      uses: actions/setup-python@v2
			with:
          go-version: ${{ env.GO_VERSION }}
        
    - name: Install Dependencies
      run: |
        make
        
  armv64_job:
    name: Build and Test for arm64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
			  with:
          go-version: ${{ env.GO_VERSION }}
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Install and Run tests
        run: |
           docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
             arm64v8/ubuntu:20.04 \
              bash -exc 'apt-get update && \
              make && \
              make check && \
              make test PKG=./sql && \
              deactivate'



