name: Test Unit

on:
  pull_request:
    branches:
      - '*'
env:
  GO_VERSION: 1.17

jobs:

  test-unit:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Tests
        run: make

  test_arm64: 
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Install and Run tests
        run: |
               docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
               arm64v8/ubuntu:20.04 \
               bash -exc 'apt-get update && \
	       make && \
	       deactivate'
